version: 0.0
os: linux

files:
  - source: /
    destination: /home/ec2-user/final-python-app
    overwrite: yes

permissions:
  - object: /home/ec2-user/final-python-app
    pattern: "**"
    owner: ec2-user
    group: ec2-user
    mode: 755

hooks:
  BeforeInstall:
    - location: scripts/install_docker.sh
      timeout: 300
      runas: root

  ApplicationStop:
    - location: scripts/stop_application.sh
      timeout: 300
      runas: ec2-user

  ApplicationStart:
    - location: scripts/start_application.sh
      timeout: 300
      runas: ec2-user
