version: 0.0
os: linux
files:
  - source: /
    destination: /home/root/final-python-app
    overwrite: yes
permissions:
  - object: /home/root/final-python-app
    pattern: "**"
    owner: root
    group: root
    mode: 755
hooks:
  BeforeInstall:
    - location: scripts/install_docker.sh
      timeout: 300
      runas: root
  ApplicationStop:
    - location: scripts/stop_application.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/start_application.sh
      timeout: 300
      runas: root